# Generated by Django 2.2.28 on 2023-06-10 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectoin_name', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='./static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.ImageField(upload_to='')),
                ('school', models.CharField(max_length=200, null=True)),
                ('class_name', models.CharField(max_length=40, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.ImageField(upload_to='')),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='./static/images')),
                ('author_name', models.CharField(max_length=40)),
                ('page_number', models.IntegerField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poco.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Books_to_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=40)),
                ('due_date', models.CharField(max_length=40)),
                ('Select_a_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poco.Books')),
                ('Select_a_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
